spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,httptrace"
logging:
  level:
    root: debug
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
---
spring:
  config:
    activate:
      on-profile: prd
    import: configserver:http://config-server:8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka/

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: trace
    org.springframework.web.reactive: trace
    org.springframework.boot.autoconfigure.web: trace
    reactor.netty: trace
    redisratelimiter: trace
