logging:
  level:
    root: debug

spring:
  application:
    name: api-gateway
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,httptrace"
---
spring:
  config:
    activate:
      on-profile: prd
  cloud:
    config:
      uri: http://config-server:8080
