logging:
  level:
    root: debug

spring:
  application:
    name: api-gateway
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,httptrace"