apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  labels:
    monitor: api-gateway
  namespace: default
spec:
  endpoints:
  - interval: 10s
    path: /actuator/prometheus
    port: management
  namespaceSelector:
    matchNames:
      - "tech-innovative"
  selector:
    matchLabels:
      svc: api-gateway
